# Site settings
title: Zhuohao (Jerry) Zhang
email: zhuohao@uw.edu
description: > # this means to ignore newlines until "baseurl:"
   I am a Ph.D. student at University of Washington, with a concentration on HCI. I mainly study and design assistive technologies.
baseurl: "" 
url: "https://www.zhuohaozhang.com" # the base hostname & protocol for your site
production_url: "https://www.zhuohaozhang.com"
github_username: saltfishzzh
permalink: /404.html

twitter:
  username: ZhuohaoZhang

sass:
  style: compressed

collections:
  publications:
    output: false

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-mentions
